# Generated by Django 6.0.1 on 2026-06-17 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='score_applied_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped'), ('rescheduled', 'Rescheduled')], max_length=20, null=True),
        ),
    ]
